### ISSUE TITLE
Violations of causal consistency found

### ISSUE THREAD

**Issue by SuperLeilia** [AntidoteDB/antidote#458] opened 2021-12-01 13:20 UTC
Hi, we have found a bug while checking causal consistency of Antidote. We have printed operations to the database and return values from database into logs.

The configurations are listed below:
- AntidoteDB 0.2.2
- 6 clients (3 clients per maachine), 20 transactions peer clients, 20 operations per transactions with 5 keys

The log file is attached at the end of this post . Note that operation is in the type of operation_type(variable, value, client_id, transaction_id).

We have found that transaction 0 can reach transaction 39 by the order in each client and write-read relation. Aiso in transaction 39 we have found w(0,62) and in transaction 0 we have found r(0,62), so transaction 39 can reach transaction 0, which made it a cycle. Obviously it violates causal consistency.

![graph](https://user-images.githubusercontent.com/23026219/144241449-c81ecfc6-6a12-4d9d-aa57-d496e17793ee.jpeg)

Datalog files FYI:
[result.txt](https://github.com/AntidoteDB/antidote/files/7633673/result.txt)

**Comment by bieniusa** [comment] 2021-12-07 10:20
Thank you @SuperLeilia!  We will try to reproduce the setup and test to debug. 
One question: What type of CRDT are you using for the reads/writes, e.g. LWWRegister?

**Comment by SuperLeilia** [comment] 2021-12-07 10:29
Hi @bieniusa , I used LWWRegister and with Python client.

**Comment by SuperLeilia** [comment] 2022-01-24 03:38
To facilitate your debugging, I attached my test code @bieniusa 

[data_generator_antidote.txt](https://github.com/AntidoteDB/antidote/files/7922433/data_generator_antidote.txt)

**Comment by peterzeller** [comment] 2022-01-26 20:45
The Antidote Python client currently does not support session guarantees, so there is no happens-before relation between operations that are executed on the same thread. Does your analysis depend on session guarantees or is it still a consistency violation? 

Session guarantees are supported in the Javascript (see https://antidotedb.github.io/antidote_ts_client/#session-guarantees) and Java (pass `CommitInfo timestamp` to a transaction).

**Comment by SuperLeilia** [comment] 2022-01-27 14:06
Thanks for your reply, @peterzeller ! Some comments/questions:

1. We followed https://github.com/AntidoteDB/antidote-python-client, as well as the official document, to deal with client-side logic (for txns). We couldn't find nowhere that python clients cannot work with causal consistency. Are we missing anything?

2. For python client, what about causal consistency at the process level (e.g., one single thread per process)? There should not be any doubt that a process itself is a session, right?

3. Are you suggesting that, to benefit from Antidote's causal consistency guarantee, we must currently use either Javascript or Java client?

Thanks!

**Comment by peterzeller** [comment] 2022-01-29 21:41
@SuperLeilia I have added the option to the python client in this PR: https://github.com/AntidoteDB/antidote-python-client/pull/4

With this change you can set the minimum snapshot time in your code like this:

    tx = clt.start_transaction(min_snapshot=clt.last_commit)

The `last_commit` field is set whenever you have committed a transaction.

> Our ops and txns are closed loop and they are definitely ordered by the program order, right?

Antidote does not use the implicit program order - you need to pass the commit timestamp from the previous operation to the next operation manually. 

I don't remember exactly why we designed it like this, but I think it was something like this: 

1. Ideally, Antidote clients would automatically fail over to different data centers if the current one cannot be reached. If you always want to enforce program-order that would mean a potential very long wait until the updates from the crashed data center are replicated to the other one. With explicit ordering the programmers have more control to state where the order is important and where it is not.
2. In many programming languages, program order is not so easy to define. With thread-pools and features like async/await you can have code that looks like it happens on one thread but actually happens on several threads.


Would be cool if you could try with the `min_snapshot` option.

**Comment by SuperLeilia** [comment] 2022-01-30 08:54
@peterzeller Thanks for your reply. 
I noticed that the new commits are on the branch session-guarantees-support. However, we install Antidote client through "pip antidotedb" and the last commit field is not added.

**Comment by bieniusa** [comment] 2022-01-30 12:22
It is on master now; I just merged the PR.

**Comment by preguica** [comment] 2022-01-30 15:25
I have uploaded the current version to pip... you should be able to use the
new version using pip now.

Annette Bieniusa ***@***.***> escreveu no dia domingo,
30/01/2022 à(s) 12:23:

**Comment by 20211202na** [comment] 2022-02-09 16:59
@preguica @bieniusa @peterzeller Thanks for fixing the python client issue!! The new version is running smoothly so far. I'll get back to you if any anomaly identified :D

**Closed** 2022-02-19 13:23 UTC
